Prefab fixes + updated scenes
renskrauweel/RumbleRacer pull request #18
Opened 2020-05-11 11:54 UTC by renskrauweel

2020-05-11 12:10 UTC, kevinhaakma submitted a review, later dismissed

2020-05-11 12:10 UTC, Richfart approved these changes

2020-05-11 13:12 UTC, Richfart requested changes
Checkpoints veranderen van geluid op basis van snelheid,
Auto prefab mist "Car" tag

2020-05-11 17:40 UTC, kevinhaakma approved these changes

2020-05-12 08:36 UTC, Richfart approved these changes

2020-05-12 08:39 UTC, merged