Added countdown and Cleaned file hierarchy
renskrauweel/RumbleRacer pull request #7
Opened 2020-05-05 20:55 UTC by kevinhaakma

2020-05-05 21:59 UTC, Richfart commented on Assets/GameManager.cs
> +        await Task.Delay(3000);
Dit is niet heel netjes, als we de timer aanpassen naar 5 seconden moet dat ook hier gebeuren.

2020-05-05 22:02 UTC, Richfart commented on Assets/Car/Scripts/Countdown/CountdownScript.cs
> +                    break;
Redundant code, is een if statement hier niet beter?

2020-05-05 22:02 UTC, Richfart requested changes
Graag ervoor zorgen dat de duur van de timer niet op 2 plaatsen staat.

2020-05-05 22:21 UTC, Richfart approved these changes
Lijkt prima!

2020-05-06 09:01 UTC, renskrauweel approved these changes

2020-05-06 09:10 UTC, merged